### ISSUE TITLE
Linter prints errors twice in Sublime status bar.

### ISSUE THREAD

**Issue by wearhere** [SublimeLinter/SublimeLinter-pylint#11]
As seen here:

![screen shot 2014-07-17 at 4 00 07 pm](https://cloud.githubusercontent.com/assets/110000/3620725/247e1b52-0e06-11e4-9c5f-30c3b1036861.png)

**Comment by jerlich** [comment]
I have the same error.
Sublime Test, Stable Channel, Build 3083
SublimeLinter v3.5.0
SublimeLinter-PyLint 1.3.1
![screen shot 2015-07-01 at 5 39 57 pm](https://cloud.githubusercontent.com/assets/2465395/8451764/421a845a-2018-11e5-8a47-ca84377b753a.png)

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.
