### ISSUE TITLE
Pylint Portable not working?

### ISSUE THREAD

**Issue by Zonker96** [SublimeLinter/SublimeLinter-pylint#22]
I used Sublime a while on my pc at home and it works fine with your pylint. Now i want a portable version of Sublime and I install the portable version... Now I getting problems with pylint. 

I can use pep8 lint, but i think pylint is mutch better, so I decide to post this issue. In this case nice work you have done yet :+1: 

My Python is on my Usb-device (root path) : "I:\Python" and sublime is in "I:\Editors\Sublime\sublime_text.exe".

The Error are by typing in my configurations "..", because when I write into paths "I:\Python" pylint works fine..

My Errors with variable Config:

>
SublimeLinter: find_windows_python: <= ../../Python\python.exe 
SublimeLinter: find_python: system python = ../../Python\python.exe 
SublimeLinter: find_python: available version = {'minor': 5, 'major': 3} 
SublimeLinter: find_python: <= ('../../Python\\python.exe', None, 3, 5) 
SublimeLinter: sys.path for ../../Python\python.exe:
I:\Python\python35.zip
I:\Python\DLLs
I:\Python\lib
I:\Python
I:\Python\lib\site-packages
>
SublimeLinter: find_python(version=None, script='pylint', module=None) 
SublimeLinter: find_python: default python = ../../Python\python.exe 
SublimeLinter: find_python: available version = {'minor': 5, 'major': 3} 
SublimeLinter: find_python: 'pylint' path = ../../Python\Scripts\pylint.exe 
SublimeLinter: find_python: <= ('../../Python\\Scripts\\pylint.exe', None, 3, 5) 
SublimeLinter: pylint version query: ../../Python\Scripts\pylint.exe --version 
SublimeLinter: pylint version: 1.5.2 
SublimeLinter: pylint: (>= 1.0) satisfied by 1.5.2 
SublimeLinter: pylint activated: ../../Python\Scripts\pylint.exe 
SublimeLinter: chdir not set or invalid, using C:\Users\Patrick\Desktop 
SublimeLinter: pylint: test.py ['../../Python\\Scripts\\pylint.exe', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n'] 
SublimeLinter: ERROR: could not launch ['../../Python\\Scripts\\pylint.exe', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n', 'C:\\Users\\Patrick\\Desktop\\test.py'] 
SublimeLinter: reason: [WinError 2] Das System kann die angegebene Datei nicht finden 
SublimeLinter: PATH: ../../Python;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\ 
Package Control: Skipping automatic upgrade, last run at 2016-01-06 23:31:15, next run at 2016-01-07 00:31:15 or after

my configuration

>
{
    "user": {
        "debug": true,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "pylint": {
                "@disable": false,
                "args": [],
                "disable": "",
                "enable": "",
                "excludes": [],
                "paths": [],
                "rcfile": "",
                "show-codes": false
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": [
                "../../Python"
            ]
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python"
        },
        "warning_color": "DDB700",
        "wrap_find": true
    }
}

The english translation of the Win error is: "the system cant find the file"

So it is a small issue and when you don't get the time to fix it, no problem. For the time, i will set my usb-device on "I:" so i can work fine :)

With greets and some english issues from germany

Tray

**Comment by NotSqrt** [comment]
Hello Tray,

I'm assuming that SublimeLinter does a few ``chdir`` as suggested by the log ``chdir not set or invalid, using C:\Users\Patrick\Desktop ``, which means that the relative path to pylint is no longer the same !

It's probably as simple as making sure that SublimeLinter transforms relative paths into absolute paths early enough when it loads the settings ..

If you feel like putting your hands in the code of SublimeLinter, have a look yourself !

Anyhow, it's worth an issue at https://github.com/SublimeLinter/SublimeLinter3, I don't think the fix is specific to SublimeLinter-pylint !

**Comment by Zonker96** [comment]
Ok thank you for your quick response.

I will set up an issue post in SublimeLinter3. But pep8 is working with realtiv paths. I have tested it and it works fine... 

Tray

**Comment by NotSqrt** [comment]
SublimeLinter-pep8 imports pep8, so it does not care about the relative path !
SublimeLinter-pylint calls the pylint program, hence the difference ..

**Comment by Zonker96** [comment]
Ok, 
I have postet an issue-post on SublimeLinter, so we can find out the issue.
https://github.com/SublimeLinter/SublimeLinter3/issues/390

**Comment by NotSqrt** [comment]
It has been developed and released !
