### ISSUE TITLE
Enhancement proposal: allow `symbolic` instead of `msg_id` for status-bar output

### ISSUE THREAD

**Issue by Hibou57** [SublimeLinter/SublimeLinter-pylint#23]
When `show-codes` is `true`, the `msg_id` of PyLint outputs are shown in the status bar. 

Pytlint gets invoked with this argument: `--msg-template='{line}:{column}:{msg_id}: {msg}'`. Trying to give it the `--msg-template='{line}:{column}:{symbolic}: {msg}'` argument in preferences is an idea, but it does not work, as then, there is not more output anymore.

So I guess this simple thing cannot only be done at the plugin level.

**Comment by NotSqrt** [comment]
The plugin needs to match the output lines !
For the moment, it checks explicitly for a regex [EWC][0-9] ..

If both are modified (potentially by using both information in the template), it can work !

**Comment by Hibou57** [comment]
Will this cause any issue, if this regex was modified? (I'm just discovering this plugin since today, I have not looked at its source so far)

**Comment by NotSqrt** [comment]
if we add something like ``(?P<symbolic>.*?:)`` in the regex before the ``message`` part, and modify the template to add ``{symbolic}:``, then no problem !
The ``symbolic`` is then available in ``split_match`` method, and where I use ``show_code`` to build the message that will appear in the status bar, we can choose to use ``code`` or ``symbolic`` or both !

**Comment by braver** [comment]
This is a "won't fix", both the code and symbolic name are now shown. In SL4 we have several modes of displaying the messages and they're all coordinated similarly for all linters, or at least we're trying to standardise a bit.
