### ISSUE TITLE
valaclinter directory path appended twice for file

### ISSUE THREAD

**Issue by Mparaiso** [SublimeLinter/SublimeLinter-pylint#24]
Hi , i'm developping a linter for vala. Here is the error I get :

    SublimeLinter: chdir not set or invalid, using
    C:\Users\user\Documents\development\github.com\mparaiso\mongodb-vapi\examples 
    SublimeLinter: valac: valalint-test.vala ['C:\\msys64\\usr\\local\\bin\\valac.exe', '-C'] 
    SublimeLinter: valac output:
    Compilation failed: 1 error(s), 0 warning(s)
    error: Unable to map file /c/Users/user/Documents/development/github.com/mparaiso/mongodb-vapi/examples/C:\Users\user\Documents\development\github.com\mparaiso\mongodb-vapi\examples\valalint-test.vala': Failed to open file '/c/Users/user/Documents/development/github.com/mparaiso/mongodb-vapi/examples/C:\Users\user\Documents\development\github.com\mparaiso\mongodb-vapi\examples\valalint-test.vala': open() failed: No such file or directory
     
    (valac:7852): GLib-CRITICAL **: g_mapped_file_get_length: assertion 'file != NULL' failed 

It seems the filepath is appended twice : once the linux filepath then the window filepath

     /c/Users/user/Documents/development/github.com/mparaiso/mongodb-vapi/examples/C:\Users\user\Documents\development\github.com\mparaiso\mongodb-vapi\examples\valalint-test.vala

here is how my linter.py file looks like :

    from SublimeLinter.lint import Linter, util
    class Valac(Linter):
        """Provides an interface to valac."""

        syntax = 'vala'
        cmd = 'valac -C '
        executable='valac'
        version_args = '--version'
        version_re = r'(?P<version>\d+\.\d+\.\d+)'
        version_requirement = '>= 0.0.1'
        regex = r'^.+?:(?P<line>\d+)\.(?P<col>\d+).+?: (?:(?P<error>error)|(?P<warning>warning)): (?P<message>.+)'
    
        multiline = False
        line_col_base = (1, 1)
        tempfile_suffix = "-"
        error_stream = util.STREAM_BOTH
        selectors = {}
        word_re = None
        defaults = {}
        inline_settings = None
        inline_overrides = None
        comment_re = None 

Edit: If I could pass only the filename to the linter I think it would help, instead of the fullpath to the file , how could I do that ? thanks.

**Comment by NotSqrt** [comment]
Please discuss this in SublimeLinter3 itself, not the individual linters.

**Comment by Mparaiso** [comment]
Fine, so where do people get help when developing their own plugin ? because it's precisely what I'm doing here.

**Comment by NotSqrt** [comment]
SublimeLinter-pylint is a linter among others, not the actual framework to develop the linters.

https://github.com/SublimeLinter/SublimeLinter3 is the place to use !

**Comment by Mparaiso** [comment]
Understood
