### ISSUE TITLE
Pylint import check when directories are not the same than the import

### ISSUE THREAD

**Issue by Amathlog** [SublimeLinter/SublimeLinter-pylint#27]
I've an unusual question, and I don't find the answer because no one is doing like that :p

I want to use PyLint in order to resolve errors before running the script, especially calling methods from other modules and heritage. So I have installed everything for Sublime Text 3. And it's working (at least I have the errors high-lightened)

Thing is, my python scripts are not organized the same way than the import. For exemple I have one module in src/project/module/file.py and the import is like that : progName.app.module. It's because scripts are precompiled (with operations done on it such as Macros replacement)

But because of that, PyLint is unable to find the folder for the right import.

I can't modify the directories hierarchy, so I have to find a way to tell PyLint that it has to find progName.app.module in src/project/module

If someone ever had this issue...

Thanks !

**Comment by NotSqrt** [comment]
Hi !

If the final code is installed somewhere, a virtualenv for instance, you can use the ``paths`` settings of sublime linter to point it to the proper ``python`` binary.

If you use ``pip install -e ...``, you can add the paths you installed that way to pylint with the setting also named ``paths`` but in the ``pylint`` section of your settings.

```json
{
	"SublimeLinter":
	{
		"linters":
		{
			"pylint":
			{
				"@disable": false,
				"paths":
				[
					"${home}/projects/my_project"
				]
			}
		},
		"paths":
		{
			"linux":
			[
				"${home}/projects/Envs/my_env/bin/python"
			],
			"osx":
			[
			],
			"windows":
			[
			]
		}
	}
}
```
