### ISSUE TITLE
set pythonpath in sublime linter 

### ISSUE THREAD

**Issue by amrit-poudel** [SublimeLinter/SublimeLinter-pylint#28]
I keep getting the following error even though I have correctly set paths and python_paths in SublimeLinter.sublime-settings. I am using ST3 with SublimeLinter 3 and SublimeLinter-pylint plugin, along with pylint v 1.4.4 and python version 2.7.9.

---

SublimeLinter: WARNING: no pylint version could be extracted from:
Traceback (most recent call last):
  File "/hpc/bin/pylint", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

---

I do not get this error in the terminal after exporting PATH and PYTHONPATH. Typing pylint --version  in the terminal correctly returns 1.4.4.

 I am sure this error would go away if I could  set the PYTHONPATH to point to my location of setuptools, but I am unable to do so from SublimeLinter.sublime-settings. "python_paths" option does not seem to be recognized at all.  "paths" option seem to work fine though. 
I will appreciate any help.
Thanks.

**Comment by NotSqrt** [comment]
Hi,

Have you followed the troubleshooting guide regarding paths : http://www.sublimelinter.com/en/latest/troubleshooting.html#debugging-path-problems ?

If you need to export ``PYTHONPATH`` in your terminal so that you can execute pylint, it's probably a good indication that pylint is not in the recommended location (installation through ``sudo pip install pylint``) and the guide should help in supporting this specific location.

Follow the troubleshooting guide, including the ``Validating your PATH`` part.

**Comment by amrit-poudel** [comment]
Thanks for your reply. 
You message seems to indicate that there is no way to specify  the PYTHONPATH (not the PATH) within sublimelinter-pylint. 

Say, I downloaded and installed pylint, setuptools, numpy, scipy etc and put them in a Desktop (which is not a standard location like /usr/local or /usr or /opt/local etc), is there really no way to set the pythonpath so that it points to Desktop? Is it really not possible to put these paths and pythonpaths in some file (other than .bashrc or .bash_profile file) and source the file to set the pythonpath?


Please note that my python libraries have no problem. They work perfectly fine.

**Comment by NotSqrt** [comment]
Sublimelinter in general needs to find the executables, so you have to put them in your path one way or another !

**Comment by amrit-poudel** [comment]
Thanks for taking your time to reply to my question.

I understand your point. That is the reason why I edit "paths" variable in SublimeLinter.sumlime-setting file. The "paths" variable works perfectly fine and it can locate where my python, pylint, etc. are. I can clearly see it can augment my PATH.

The problem however is "python_paths" variable in the same SublimeLinter.sumlime-setting file. Of course, I set "python_paths" variable to point to wherever my pylint, setuptools, etc. packages are. However, this "python_paths" variable does *not* seem to work the way it should. It simply *cannot* augment my PYTHONPATH, unlike the "paths" variable which *can* augment my PATH.


I understand that I could set everything up in a .bash_profile/bashrc file. However, I would like to avoid using .bash_profile/.bashrc file for other reasons. I would like to be able to do this within SublimeLinter.sumlime-setting file, because that is the whole point of having a "setting file" so that user can set PATH, PYTHONPATH, etc. without having to touch .bash_profile/.bashrc file.

Therefore, my question is: Is there a way to set PYTHONPATH variable, just like PATH variable, in SublimeLinter.sumlime-setting file so that my pythonpath is augmented ?  

Thanks.

**Comment by NotSqrt** [comment]
That's outside my grasp of how sublimelinter manipulates the PYTHONPATH.
You might ask at https://github.com/SublimeLinter/SublimeLinter3 for more help.

Regards.

**Comment by braver** [comment]
We have been making [many changes](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.0.0-rc.1.txt) to SublimeLinter, some of which also should have fixed this particular problem. It would be really nice if you could [try the beta](https://github.com/SublimeLinter/SublimeLinter/tree/15bb4a2e2024a623f60bb444eadd5790764fdfb9#sublimelinter-4-beta) and let us know if that fixes the problem for you.

**Comment by nabinkhadka** [comment]
Why is this closed?

**Comment by braver** [comment]
> We have been making many changes to SublimeLinter, some of which also should have fixed this particular problem.
