### ISSUE TITLE
Fix for PythonImproved 

### ISSUE THREAD

**Issue by LeonardoGentile** [SublimeLinter/SublimeLinter-pylint#29]
I'm using https://github.com/MattDMo/PythonImproved as syntax definition for python.
The plugin just does nothing in this case even if manually asking for linting the current file, most probably because it's [specifically looking ](https://github.com/SublimeLinter/SublimeLinter-pylint/blob/master/linter.py#L20) for the `python` syntax.

This settings fixed things for me under `Packages/User/SublimeLinter.sublime-settings`

```
"syntax_map": {
  "pythonimproved": "python"
}
```

I guess you could change `syntax = 'python'` with `syntax = ('python', 'pythonimproved')` 

Thanks for this btw 👍

**Comment by braver** [comment]
These days we solve that with the [selector setting](https://github.com/SublimeLinter/SublimeLinter/blob/master/docs/linter_settings.rst#selector).
