### ISSUE TITLE
Seems pylint ignoring max-line-length setting

### ISSUE THREAD

**Issue by kiddick** [SublimeLinter/SublimeLinter-pylint#33]
Althoutht I set that in config file:

```
            "pylint": {
                "@disable": false,
                "args": [],
                "disable": "",
                "enable": "",
                "excludes": [],
                "max-line-length": 120,
                "paths": [],
                "rcfile": "",
                "show-codes": false
            }
```

In ST3 console log I am getting this for running pylint:
```
SublimeLinter: pylint: check_file.py ['/usr/bin/python', '/home/me/.local/bin/pylint', "--msg-template='{line}:{column}:{msg_id}: {msg}'", '--module-rgx=.*', '--reports=n', '--persistent=n'] 
```

**Comment by NotSqrt** [comment]
New keys in the "pylint" dict don't get automagically added to the command !

However, you can use:
```python
            "pylint": {
                "@disable": false,
                "args": ["--max-line-length=120"],
                "disable": "",
                "enable": "",
                "excludes": [],
                "paths": [],
                "rcfile": "",
                "show-codes": false
            }

**Comment by kiddick** [comment]
@NotSqrt thank you for quick reply.
I've delete pylint to perform some tests.
So I have another linter installed `pep8 (pycodestyle)`.
And here is the same behavior: seems settings are ignored. Looks like it more wide issue.

**Comment by kiddick** [comment]
Nevermind. It works for `pep8` linter somehow (I mean dict setting `"max-line-length": 120,`).
And your work around works pretty well for pylint.

**Comment by kiddick** [comment]
> New keys in the "pylint" dict don't get automagically added to the command !
Is it correct?
Why in other linter plugins that works correct with settings in dict (not in "args").

**Comment by NotSqrt** [comment]
For instance, the pep8 linter already has a `"max-line-length"` key !
