### ISSUE TITLE
SublimeLinter: WARNING: pylint deactivated, cannot locate '' 

### ISSUE THREAD

**Issue by dchouren** [SublimeLinter/SublimeLinter-pylint#41]
Searched previous threads but nothing I found fixes this error. Anyone able to help?

I can run pylint using Terminal (Mac Sierra)

> which pylint
> /Users/daway/miniconda3/envs/kharon/bin/pylint
> 

I am using Python 3.6 from a virtualenv

> which python
> /Users/daway/miniconda3/envs/kharon/bin/python

> which -a python
> /Users/daway/miniconda3/envs/kharon/bin/python
> /Users/daway/miniconda3/bin/python
> /Users/daway/miniconda3/bin/python
> /usr/bin/python
> /Users/daway/miniconda3/bin/python

SublimeLinter.sublime-settings
> "paths": {
>             "linux": [],
>             "osx": ["/Users/daway/miniconda3/envs/kharon/bin/pylint"],
>             "windows": []
>         },
>         "python_paths": {
>             "linux": [],
>             "osx": ["/Users/daway/miniconda3/envs/kharon/bin/python3.6"],
>             "windows": []
>         },

SublimeLinter.sublime-settings -- User

> "pylint": {
>                 "@disable": false,
>                 "@python": 3.6,
>                 "args": [],
>                 "disable": "",
>                 "enable": "",
>                 "excludes": [],
>                 "paths": [],
>                 "rcfile": "",
>                 "show-codes": false
>             },
> 

and

> "paths": {
>             "linux": [],
>             "osx": [
>                 "/Users/daway/miniconda3/envs/kharon/bin/pylint"
>             ],
>             "windows": []
>         },
>         "python_paths": {
>             "linux": [],
>             "osx": [
>                 "/Users/daway/miniconda3/envs/kharon/bin/python3.6"
>             ],
>             "windows": []
>         },

The sublime console output:
>
startup, version: 3143 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/daway/Library/Application Support/Sublime Text 3/Packages
state path: /Users/daway/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/daway/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.272384
using gpu buffer for window
font face "" could not be found, defaulting to "Menlo"
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
using gpu buffer for window
startup time: 0.713943
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SublimeLinter-pylint.linter
SublimeLinter: pylint linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
reloading plugin SummitEditor.build
reloading plugin SummitEditor.completions
reloading plugin SummitEditor.linter_install
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/xl/gfzrh7wx7wbdvpltpzq80dm40000gn/T/SublimeLinter3-daway 
SublimeLinter: find_python(version='3', script=None, module=None) 
SublimeLinter: find_python: requested version = {'minor': None, 'major': 3} 
SublimeLinter: user shell: /bin/bash 
SublimeLinter: computed PATH using /bin/bash:
/Users/daway/miniconda3/envs/kharon/bin/pylint
/usr/texbin
/Users/daway/anaconda3/bin
/opt/local/bin
/opt/local/sbin
/Users/daway/miniconda3/envs/kharon
/usr/local/bin
/usr/local/cuda/bin
/Users/daway/miniconda3/envs/kharon/bin/pylint
/Users/daway/miniconda3/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/TeX/texbin
/usr/local/share/dotnet
/Library/Frameworks/Mono.framework/Versions/Current/Commands
 
SublimeLinter: find_posix_python: python3 => /Users/daway/miniconda3/bin/python3 
SublimeLinter: find_python: system python = /Users/daway/miniconda3/bin/python3 
SublimeLinter: find_python: available version = {'minor': 6, 'major': 3} 
SublimeLinter: find_python: <= ('/Users/daway/miniconda3/bin/python3', None, 3, 6) 
SublimeLinter: sys.path for /Users/daway/miniconda3/bin/python3:
/Users/daway/miniconda3/lib/python36.zip
/Users/daway/miniconda3/lib/python3.6
/Users/daway/miniconda3/lib/python3.6/lib-dynload
/Users/daway/miniconda3/lib/python3.6/site-packages
/Users/daway/miniconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg
 
environment variables loaded using: /bin/bash -l
Package Control: No updated packages
SublimeLinter: find_python(version=None, script='pylint', module=None) 
SublimeLinter: find_python: default python = /Users/daway/miniconda3/bin/python 
SublimeLinter: find_python: available version = {'minor': 6, 'major': 3} 
SublimeLinter: find_python: 'pylint' path = None 
SublimeLinter: find_python: <= (None, None, 3, 6) 
SublimeLinter: WARNING: pylint deactivated, cannot locate '' 
reloading settings Packages/User/SublimeLinter.sublime-settings
reloading /Users/daway/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings
reloading /Users/daway/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings
reloading /Users/daway/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings
reloading /Users/daway/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings
`

Thanks!

**Comment by NotSqrt** [comment]
I think the paths you declared should point to the folders containing the programs pylint or python, not the actual programs.
Can you try that ?

**Comment by dchouren** [comment]
Fixed, thanks!
