### ISSUE TITLE
Installing via package control doesn't work due to cert issues

### ISSUE THREAD

**Issue by Mirekkukla** [SublimeLinter/SublimeLinter-pylint#43]
`SublimeLinter-pylint` is not available for installation via package control in sublimetext3, and doesn't show up when searching:

![image](https://user-images.githubusercontent.com/903370/36617263-9e017f0c-189b-11e8-83a5-830b33d59e4b.png)

When visiting the main package control page (https://packagecontrol.io/packages/SublimeLinter-pylint), you'll find that there's an invalid certificate that needs to be updated: 

![image](https://user-images.githubusercontent.com/903370/36617198-5bbf5f7e-189b-11e8-907e-5153caa4fa15.png)

Not exactly sure what the fix is, but folks will be unable to install this package via package control until its resolved.

**Comment by braver** [comment]
This is a package control issue, nothing we can do here.
