### ISSUE TITLE
Unable to find via Package Control

### ISSUE THREAD

**Issue by Shatnerz** [SublimeLinter/SublimeLinter-pylint#44]
I'm not sure if this is the right place, but I am unable to install SublimeLinter-pylint via Package Control in Sublime Text 3. This is weird considering it is located here: https://packagecontrol.io/packages/SublimeLinter-pylint

This is all that I am seeing.

![image](https://user-images.githubusercontent.com/6402887/37299774-9cc04cec-25fa-11e8-9d42-75edd582bf2b.png)

Any help would be appreciated.

**Comment by NotSqrt** [comment]
Are you sure it's not already installed ?

**Comment by Shatnerz** [comment]
Let's just say this was a little embarrassing. It's been a long day.

**Comment by kaste** [comment]
😁
