### ISSUE TITLE
Useless error message when config file exists

### ISSUE THREAD

**Issue by atauzki** [SublimeLinter/SublimeLinter-pylint#46]
I use a .pylintrc file for global pylint configuration, but pylint always show:
```
SublimeLinter: #1 pylint test.py ERROR:
================================================

Using config file C:\Users\HP\.pylintrc
```

**Comment by kaste** [comment]
Oh. 😮 

This can be fixed relatively simple here

https://github.com/SublimeLinter/SublimeLinter-pylint/blob/c923854796fcf48f44786daf1c6fe33ed8c6049a/linter.py#L34-L40

where we filter these stderr messages pylint generates.

**Comment by kaste** [comment]
That being said, we appreciate any contributions. Please consider making a pull request. It is the quickest way to have the issue resolved.
