### ISSUE TITLE
It doesn't work with pylint_django

### ISSUE THREAD

**Issue by ArtemBernatskyy** [SublimeLinter/SublimeLinter-pylint#53]
Hi, awesome package but

I've installed it with `pylint-django` and it simply refuses to use it.

(It shows warnings for Meta class for example)

Here is how i execute it `SublimeLinter.sublime-settings -- User`

```
{
  "linters": {
    "pylint": {
      "args": ["--load-plugins=pylint_django"]
    }
  }
}

```

PS when i try to add `"disable": true,` it actually disables `pylint` and when i mispell `pylint_django2` it throws an errors (i mean that it actually reads settings)  

Thx for any help !

**Comment by kaste** [comment]
Hi @ArtemBernatskyy!

Does this work on the command line? If it doesn't it's best to first ask on stackoverflow bc I don't use that plugin and there is just a wider audience over there. 

If it does work on your command line, compare the actual command you use on the cli with the command SublimeLinter executes. So see the SublimeLinter command, enable debug mode in the SublimeLinter settings and open the Sublime Console.

**Comment by ArtemBernatskyy** [comment]
Yes it's a problem with `pylint_django` or ??? something else ).

Because i've executed it via `cmd` and via sublime linter and the results are the same.
Closing it, thx @kaste for help and detailed explanation.
