### ISSUE TITLE
pylint results in errors using `extension-pkg-whitelist` on packages with deprecated members

### ISSUE THREAD

**Issue by CrepeGoat** [SublimeLinter/SublimeLinter-pylint#59]
# Versions
- Sublime: 3.2.2
- Sublime build: 3211
- SublimeLinter: 4.14.0
- SublimeLinter-pylint: 1.5.2
- pylint==1.9.5
- astroid==1.6.6
- Python interpreter running pylint: CPython 2.7.16

# Problem Description
Specifically, I am running pylint on a file that imports wxPython4. With no configuration file, pylint fails to resolve imports and reports errors on all wx imports, so I created a config file (reran to check consistency, same results up to this points) and added `extension-pkg-whitelist=wx` to the config.

Under this configuration file, the script now seems to generate `wxPyDeprecationWarning`'s (a `wx` warning type derived from `DeprecationWarning`) when run, which causes the pylint linter to fail in Sublime, reporting errors *in the linter*. However, if I run pylint in the same file from the command line, the warnings still get generated *but the program completes successfully* and generates the lints I'm looking for.

# Workaround
My current workaround is to edit the source for `astroid` directly to hide any `DeprecationWarning`'s when accessing module members. Specifically, in astroid.raw_building, I made these changes:

```diff
17a18
> import warnings
282,283c283,286
<                 member = getattr(obj, name)
<             except AttributeError:
---
>                 with warnings.catch_warnings():
>                     warnings.filterwarnings('error')
>                     member = getattr(obj, name)
>             except (AttributeError, DeprecationWarning):
```

# Moving Forward
As I am not a contributor to this codebase, I leave any decisions on how to address this to the maintainers.

**Comment by kaste** [comment]
Hi 👋!

I guess pylint puts these warnings on stderr, normal results come in on stdout.  We handle stderr and already filter some common output. Please take a look a linter.py "on_stderr".  In particular, we just need a good enough regex and some example output to fix this.

Maybe you could help here 🙏

**Comment by CrepeGoat** [comment]
I'm down to help, for sure :) here's the warning output for my error (should've put this in the prompt to start with, sorry):

```
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:284: wxPyDeprecationWarning: Accessing deprecated property. Use altDown instead.
  member = getattr(obj, name)
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:284 wxPyDeprecationWarning: Accessing deprecated property. Use controlDown instead.
  member = getattr(obj, name)
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:284: wxPyDeprecationWarning: Accessing deprecated property. Use metaDown instead.
  member = getattr(obj, name)
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:284: wxPyDeprecationWarning: Accessing deprecated property. Use shiftDown instead.
  member = getattr(obj, name)
```

(tbh the fact that it pulls errors through the terminal output and not directly from the interpreter, or even through error codes (which it turns out are determined by [the infractions pylint catches](https://docs.pylint.org/en/1.6.0/run.html#exit-codes), and not it's run status), is kind of a shame. It makes the fixes feel like hacks...)

Regarding a regex, here are my thoughts:
- if you want to catch *all warnings*, the only commonality among warning messages is that they contain the word "Warning" from when the warning class' name is printed. It's not a strict guarantee but will probably do the job.
- if you want to catch *only deprecation warnings*, same thing as above w/ "DeprecationWarning".
- if you want to catch deprecation warnings *for explicitly this situation*, you could also include the parts of the output re: the `astroid` package:
  - the file path "\astroid\\"
  - not sure if "site-packages" always precedes that? but that could go in too
  - "raw_building.py" works for this version, and maybe every current `astroid` version available, but is still subject to change unexpectedly. So I don't recommend including this,
  - line number ":284", same as above but even more so
  - the following code line "`member = getattr(obj, name)`"; same issue as above

What do you think?

In the meantime, I think I'll submit this as a bug to the `astroid` dev's; it may not be desirable to have the code pushing warnings when walking a project's members, and if they fix it then this issues kind of disappears. I'll log any progress in this thread.

**Comment by kaste** [comment]
I'm surprised by this output, probably I don't follow.  You have this output from the Terminal, right?  What actually happens in SublimeLinter? Maybe I should have asked more.

> Under this configuration file, the script now seems to generate ... [warnings] ... when run, which causes the pylint linter to fail in Sublime, reporting errors in the linter. 

What does "reporting errors in the linter" mean?  What does "causes pylint to fail" mean. Do you get an error popup? Or the status bar indicating "(erred)". 

SublimeLinter actually does not (iirc) look at the exit code.  (But it doesn't like text on stderr because pylint usually outputs on stdout.)

I'm also a bit confused about "extension-pkg-whitelist".  Is this also necessary for usage on the command line, or is this a specific hack for SublimeLinter?  (pylint can see other libs, it is just "wx" that causes the problem?)

**Comment by CrepeGoat** [comment]
> You have this output from the Terminal, right?

The terminal output from running pylint directly is this (abbreviated for simplicity):

```
(venv-py2) $ python -m pylint PATH_TO_FILE\FILE.py
Using config file C:\PATH_TO_PROJECT\.pylintrc
************* Module PATH_TO_FILE\FILE
C: 49, 0: Exactly one space required around assignment
                cancelled=False
                         ^ (bad-whitespace)
C: 51, 0: Exactly one space required around assignment
            cancelled=True
                     ^ (bad-whitespace)
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:285: wxPyDeprecationWarning: Accessing deprecated property. Use altDown instead.
  member = getattr(obj, name)
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:285: wxPyDeprecationWarning: Accessing deprecated property. Use controlDown instead.
  member = getattr(obj, name)
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:285: wxPyDeprecationWarning: Accessing deprecated property. Use metaDown instead.
  member = getattr(obj, name)
C:\PATH_TO_PROJECT\venv-py2\lib\site-packages\astroid\raw_building.py:285: wxPyDeprecationWarning: Accessing deprecated property. Use shiftDown instead.
  member = getattr(obj, name)
C: 26, 0: Constant name "progress_style" doesn't conform to UPPER_CASE naming style (invalid-name)
...
[other lints listed here]
...
------------------------------------------------------------------
Your code has been rated at 3.41/10 (previous run: 3.41/10, +0.00)
```

> What actually happens in SublimeLinter?

Here's a screencap of the output in Sublime:

![Annotation 2020-04-25 161445](https://user-images.githubusercontent.com/5862803/80289968-3bc1bb00-8710-11ea-9c3e-a821304f09a1.png)

> What does "reporting errors in the linter" mean? What does "causes pylint to fail" mean. Do you get an error popup? Or the status bar indicating "(erred)".

pylint is a linter. It's job is to report "errors" as a part of its expected functionality. But if the pylint code itself raises an error when running, this is also an "error" that is *not* a part of its expected functionality, and will "cause pylint to fail", meaning the process will terminate without completing execution. I'm trying to find some terminology to use that distinguishes from these two very different "errors" with the exact same name.

> "extension-pkg-whitelist". Is this also necessary for usage on the command line, or is this a specific hack for SublimeLinter? (pylint can see other libs, it is just "wx" that causes the problem?)

`extension-pkg-whitelist` is required to resolve `wx` imports correctly.

**Comment by kaste** [comment]
Ok, sorry for my confusion. Looks exactly how I first understood the issue. Maybe I just don't like that pylint throws these depreciation warnings. I would prefer if it wouldn't. 🤪

**Comment by kaste** [comment]
How about we just add

```
stderr = re.sub('(?m)^.*DeprecationWarning.*\n.*\n', '', stderr)
```
after

https://github.com/SublimeLinter/SublimeLinter-pylint/blob/798bf4fd856fda8870a8a88b76ef330d404c6076/linter.py#L29

**Comment by CrepeGoat** [comment]
Hey! So they liked [my ticket to fix this in astroid](https://github.com/PyCQA/astroid/issues/770); it'll obviate the fix here *for new versions of pylint*. Do you think the fix you suggested would still be a good addition in order to support *older* pylint versions?

**Comment by CrepeGoat** [comment]
Regarding the fix itself, it's probably the best way to do the job?

The only downside is that it would also ignore any `DeprecationWarning`s that come from *pylint's code* (for example, [the bug in this old astroid issue](https://github.com/PyCQA/astroid/issues/681)). If that's unacceptable (I don't know if it is, maybe it's fine), then you could maybe include the literal code line that goes afterwards? So some regex like `(?m)^.*DeprecationWarning.*\n.*member = getattr\(obj, name\)\n$`? But then it depends on that line of the code never changing, so that's not great either. Maybe this is better though, because it will allow false positives (e.g., letting dep warnings through if asteroid changes that line of code) instead of false negatives (e.g., blocking genuine dep warnings originating in pylint)?

Neither are perfect, I don't think a "perfect" solution exists, either would be better than having nothing. I'll leave the decision to you ;)

**Comment by kaste** [comment]
In the context of an editor, I don't think `DeprecationWarning`s are helpful at all, so I'm more 👍 to strip them. 

So, hacking on this little plugin here, is trivial.  Just open the `Packages` folder. (E.g. from the main menu `Preferences > Browse Packages`.) Open a `cmd` here, and `git clone https://github.com/SublimeLinter/SublimeLinter-pylint.git`.  This will immediately take precedence over the "installed" one. Just add that line or a different one to `linter.py`. The linter will hot-reload on save, so that you see if it works immediately.  Commit to a new branch, and push it.  

I don't use wx nor pylint, so we ❤️ contributions.

**Comment by CrepeGoat** [comment]
Sounds good! My schedule's been really weird with everything going on in the states, so I may not get to this immediately. I'll try to have something in by the end of this weekend. If you don't hear from me by then, feel free to ping me :)

**Comment by kaste** [comment]
Ping as requested 👋

**Comment by CrepeGoat** [comment]
ping acknowledged, thanks :) this weekend, for sure this time :|
