### ISSUE TITLE
"excludes" setting is ingored

### ISSUE THREAD

**Issue by lsiden** [SublimeLinter/SublimeLinter-pylint#60]
In SublimeLinter.sublime-settings I have: 
    
    "PythonLinter": {
         "excludes": ["test_*.py"],
        ...
    }

but it still produces warnings in files that match. 

Not seeing any error messages in console.

**Comment by kaste** [comment]
Hi! The settings structure is different. Under the key "linters" comes another dict where you config individual linters. Here the name of the linter is just "pylint". Always the name you also see in the statusbar. We have some links about the settings in the Readme you might want to follow.

**Comment by kaste** [comment]
Closing as hopefully resolved.
