### ISSUE TITLE
ValueError: generator already executing

### ISSUE THREAD

**Issue by niosus** [SublimeLinter/SublimeLinter-pylint#64]
Hello! I'm sorry if this is a bit of an ignorant thing to ask, but I keep bumping into this. When I modify some files, I run into the following error:
```
SublimeLinter: #34 pylint checker.py ERROR:
===========================================

Exception ignored in: <generator object infer_attribute at 0x7f3205671350>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/astroid/inference.py", line 319, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
ValueError: generator already executing
```

It looks like it stems from pylint, but I am not entirely sure here. Does anybody have any ideas what might be happening here? Is that the analysis takes too long and two parallel pylints try to run at the same time? If there are no ideas straight away, I will try to provide a minimal example to reproduce this.

**Comment by kaste** [comment]
Yes, that's coming from pylint itself.  We might run pylint in parallel but if so in separate processes.  More or less likely you found a bug in astroid.

**Comment by niosus** [comment]
@kaste thanks for this response! I will probably then close this issue and try to create one in astroid once I have a way to reproduce this.
