### ISSUE TITLE
SublimeLinter: #15 pylint XXXXXXX.py ERROR: How to disable this if possible?

### ISSUE THREAD

**Issue by tetoNidan** [SublimeLinter/SublimeLinter-pylint#65]
So this message about 

Warning: Mismatch between the program and library build versions detected. 

pops up at the bottom when pylint is ran. It's not their console but same area. I can see how this is useful if you don't spend all your time in a terminal. Since I do however this message that pops up every save and takes up a good chunk of screen. The code in question runs fine in the terminal. I get the exact same error only once if you are importing from the file and at the head of the terminal output when run. 

Don't really see any way to disable this though in sublimeLinter settings but it's easy to miss things. 

I get that I need to sort out this wx dependency error.  I know that's the real fix. It looks like some program is using an older version of wxWidgets or something. I'll get to that to.

Any way just looking for a way to unclutter the editor a bit and cut down on repetitive tasks, thanks.

**Comment by kaste** [comment]
Sorry.  I completely missed this issue here.  🤷

**Comment by tetoNidan** [comment]
No worries, not sure it's still happening? I don't have any wxPython projects going on right now. Also I use pyenv now so I doubt that I would be getting that conflict between versions anymore.  

I just installed wxpython to a venv and ran some simple code and this issue is not there any more.

I do believe this was from when I was using Manjaro and not using pyenv so I believe I might have been installing conflicting wxpython versions for the system version of python some other app was using. Probably not the best thing to do in an arch based system!

The solution is pyenv to manage and separate and manage different versions of python! Thanks for your response and sorry for what was obviously operator error. I'm going to close this!
