### ISSUE TITLE
Teacher! Hello, is it possible to update the Pylint library to work with the latest Python version for static analysis.

### ISSUE THREAD

**Issue by zhouxinghong** [SublimeLinter/SublimeLinter-pylint#67]
Teacher! Hello, is it possible to update the Pylint library to work with the latest Python version for static analysis.

**Comment by zhouxinghong** [comment]
Is it possible to add official links for warning messages, e.g.:
pylint: warning
C0116 - Missing function or method docstring (missing-function-docstring)
![image](https://github.com/SublimeLinter/SublimeLinter-pylint/assets/54253524/1c34e4e6-3678-4bfe-9a01-4fc22efcb306)

**Comment by kaste** [comment]
Hi!  We thought about adding direct links to the documentation but only a few linters have good documentation per rule.  Basically it was hard to get a generalized solution for this.  Does Pylint have a simple URL we can construct from the error code/rule name?   

> is it possible to update the Pylint library to work with the latest Python version for static analysis.

Don't know what you mean here.  What errors do you see?

**Comment by zhouxinghong** [comment]
> Hi! We thought about adding direct links to the documentation but only a few linters have good documentation per rule. Basically it was hard to get a generalized solution for this. Does Pylint have a simple URL we can construct from the error code/rule name?
> 
> > is it possible to update the Pylint library to work with the latest Python version for static analysis.
> 
> Don't know what you mean here. What errors do you see?

Would it be possible to consider updating to the latest pylint library?

**Comment by kaste** [comment]
We don't ship a specific pylint library or version with this plugin.  We actually execute whatever version you have installed, be it globally or in a virtual environment. That's why I'm asking.

**Comment by zhouxinghong** [comment]
Because I see that vscode is constantly updating pylint.

**Comment by zhouxinghong** [comment]
If the extension can keep up with the latest release of pylint's libraries, then there's nothing to worry about.

**Comment by kaste** [comment]
I think this can be closed then.
