### ISSUE TITLE
Virtualenv

### ISSUE THREAD

**Issue by generalov** [SublimeLinter/SublimeLinter-pylint#7]
How to configure the plugin to work with projects and virtualenv?

I have a project directory `/tmp/projects/project/` and its virtualenv in `/tmp/projects/python/` wich dependencies installed.

I put `.sublimelinterrc` in the project root `/tmp/projects/project/.sublimelinterrc`:

```
{
"@python": "/tmp/projects/python/bin/python" 
}
```

When I open any *.py file in sublime-3 under project directory I see linter warnings "Unable import module ..." , and message in the sublime console:

```
SublimeLinter: pylint activated: ('/usr/bin/python', '/usr/bin/pylint')
```

It is meens that wrong python binary is used by pylint?

**Comment by posita** [comment]
@aparajita, this is not a duplicate of SublimeLinter/SublimeLinter3#70. `SublimeLinter-pylint` does not honor the setting from `.sublimelinterrc` (although `SublimeLinter-flake8` seems to work).

**Comment by aparajita** [comment]
@posita I am not the maintainer, address this to @NotSqrt .
